### PR TITLE
Remove unneeded `.laminas-ci.json`

### PR DESCRIPTION
**Pull request by TimWolla**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

All dependencies support PHP 8.3.

### CODE REVIEW

**Comment by Ocramius** [comment]
Let's please also revert #52 then :)

**Comment by TimWolla** [comment]
Are you sure about this? I find it useful preserving the entry there, because I expect there will be future PHP versions where `.laminas-ci.json` might be reintroduced and folks *are* going to forget about re-adding the entry then.

**Comment by Ocramius** [comment]
If it's gone, it's gone: let's not leave a mucus trail behind :D 

Distributing it is also not really a bug, just a minor nuisance.

**Comment by TimWolla** [comment]
> If it's gone, it's gone: let's not leave a mucus trail behind :D

Okay reverted, discussing this is neither worth your, nor my time :grin: 

> Distributing it is also not really a bug, just a minor nuisance.

Yeah. In my case we vendor all upstream dependencies *and also* review all upstream changes, because we want to know what we ship. Any additional file or change is annoying there. It also saves a (tiny) bit of traffic not including the file which generally is a good thing.

**Comment by Ocramius** [comment]
Thanks @TimWolla!

**Pull request merged**
