### PR TITLE
Support PHP 8.1

### PR DESCRIPTION
**Pull request by Ocramius**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
This patch introduces PHP 8.1 support, and bumps all dev-dependencies,
so that we are sure that the whole stack is PHP 8.1-compatible.

### CODE REVIEW

**Review by boesing — APPROVED** [review]
LGTM. Can we put this into 1.x and merge-up to 2.x? 2.x is not yet fully supported by mezzio and thus the majority of consumers may not benefit from this until mezzio v4.

**Comment by Ocramius** [comment]
IMO release here - `1.x` can be patched separately, if needed?

**Comment by Ocramius** [comment]
actually, merge-up is a compelling argument: will try this - gimme a few :-)

**Comment by Ocramius** [comment]
Changed target - will attempt a rebase after my morning meeting marathon

**Comment by Ocramius** [comment]
:ship: 

Will merge-up with all the `composer.lock` goodness too

**Pull request merged**
